apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zhaufp6yn-go 
  janus-idp.io/tekton: zhaufp6yn-go
  backstage.io/kubernetes-id: zhaufp6yn-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zhaufp6yn-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  